In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
train_dataset =pd.read_csv("train.csv", encoding="ISO-8859-1")
train_dataset.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

## Explotary Data Analaysis (EDA)

### Preprocessing

In [3]:
## Check the information about the training set

In [4]:
train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [5]:
## Check the duplicated entries of the training set

In [6]:
train_dataset.duplicated().sum()

0

In [7]:
## Get the value counts of keyword column

In [8]:
train_dataset['keyword'].value_counts()

keyword
fatalities               45
deluge                   42
armageddon               42
sinking                  41
damage                   41
                         ..
forest%20fire            19
epicentre                12
threat                   11
inundation               10
radiation%20emergency     9
Name: count, Length: 221, dtype: int64

In [9]:
## Get the value counts of location column

In [10]:
train_dataset['location'].value_counts()

location
USA                    104
New York                71
United States           50
London                  45
Canada                  29
                      ... 
Montr̩al, Qu̩bec       1
Montreal                 1
ÌÏT: 6.4682,3.18287      1
Live4Heed??              1
Lincoln                  1
Name: count, Length: 3341, dtype: int64

In [11]:
train_dataset['location']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
7608    NaN
7609    NaN
7610    NaN
7611    NaN
7612    NaN
Name: location, Length: 7613, dtype: object

In [12]:
## check the null values of the keyword column

In [13]:
train_dataset['keyword'].isnull().sum()

61

In [14]:
## check the null values of the location column

In [15]:
train_dataset['location'].isnull().sum()

2533

In [16]:
## fill the nul values

In [17]:
 train_dataset['location'].fillna('Canada', inplace=True)
 train_dataset['keyword'].fillna('radiation%20emergency', inplace=True)

In [18]:
train_dataset.head()

id                keyword location  \
0   1  radiation%20emergency   Canada   
1   4  radiation%20emergency   Canada   
2   5  radiation%20emergency   Canada   
3   6  radiation%20emergency   Canada   
4   7  radiation%20emergency   Canada   

                                                text  target  
0  Our Deeds are the Reason of this #earthquake M...       1  
1             Forest fire near La Ronge Sask. Canada       1  
2  All residents asked to 'shelter in place' are ...       1  
3  13,000 people receive #wildfires evacuation or...       1  
4  Just got sent this photo from Ruby #Alaska as ...       1

In [19]:
train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7613 non-null   object
 2   location  7613 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


#### Text Preprcoessing

In [20]:
import re
import string

In [21]:
train_dataset['text'].head()

0    Our Deeds are the Reason of this #earthquake M...
1               Forest fire near La Ronge Sask. Canada
2    All residents asked to 'shelter in place' are ...
3    13,000 people receive #wildfires evacuation or...
4    Just got sent this photo from Ruby #Alaska as ...
Name: text, dtype: object

In [22]:
train_dataset['keyword'].head()

0    radiation%20emergency
1    radiation%20emergency
2    radiation%20emergency
3    radiation%20emergency
4    radiation%20emergency
Name: keyword, dtype: object

In [23]:
train_dataset['location'].head()

0    Canada
1    Canada
2    Canada
3    Canada
4    Canada
Name: location, dtype: object

In [24]:
## convert the uppercase letters into the lowercase letters

In [25]:
train_dataset['text'] = train_dataset['text'].apply(lambda x:" ".join(x.lower() for x in x.split()))
train_dataset['text']

0       our deeds are the reason of this #earthquake m...
1                  forest fire near la ronge sask. canada
2       all residents asked to 'shelter in place' are ...
3       13,000 people receive #wildfires evacuation or...
4       just got sent this photo from ruby #alaska as ...
                              ...                        
7608    two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @thetawniest the out of control w...
7610    m1.94 [01:04 utc]?5km s of volcano hawaii. htt...
7611    police investigating after an e-bike collided ...
7612    the latest: more homes razed by northern calif...
Name: text, Length: 7613, dtype: object

In [26]:
train_dataset['location']=train_dataset['location'].apply(lambda x:" ".join(x.lower() for x in x.split()))
train_dataset['location'].iloc[100:200]

100                         uk
101             nairobi, kenya
102    instagram - @heyimginog
103                        304
104                switzerland
                ...           
195        || c h i c a g o ||
196                     canada
197                      l. a.
198                     canada
199                     canada
Name: location, Length: 100, dtype: object

In [27]:
## Remove the links

In [28]:
train_dataset['text']=train_dataset['text'].apply(lambda x: " ".join(re.sub(r'^https?:\/\/.*[\r\n]*','',x,flags=re.MULTILINE) for x in x.split()))
train_dataset['text'].head()

0    our deeds are the reason of this #earthquake m...
1               forest fire near la ronge sask. canada
2    all residents asked to 'shelter in place' are ...
3    13,000 people receive #wildfires evacuation or...
4    just got sent this photo from ruby #alaska as ...
Name: text, dtype: object

In [29]:
## Remove Punctuations

In [30]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [31]:
def remove_puncutations_of_text(text):
    for punctuation in string.punctuation:
        text=text.replace(punctuation, '')
    return text
train_dataset['text']=train_dataset['text'].apply(remove_puncutations_of_text)

In [32]:
train_dataset['text'].head()

0    our deeds are the reason of this earthquake ma...
1                forest fire near la ronge sask canada
2    all residents asked to shelter in place are be...
3    13000 people receive wildfires evacuation orde...
4    just got sent this photo from ruby alaska as s...
Name: text, dtype: object

In [33]:
def remove_punctuations_of_location(text):
    for punctuations in string.punctuation:
        location=text.replace(punctuations,'')
    return location
train_dataset['location']=train_dataset['location'].apply(remove_punctuations_of_location)

In [34]:
train_dataset['location'].head()

0    canada
1    canada
2    canada
3    canada
4    canada
Name: location, dtype: object

In [35]:
def remove_punctuations_of_keyword(text):
    for punctuations in string.punctuation:
        keyword=text.replace(punctuations,'')
    return keyword
train_dataset['keyword']=train_dataset['keyword'].apply(remove_punctuations_of_keyword)

In [36]:
train_dataset['keyword'].head()

0    radiation%20emergency
1    radiation%20emergency
2    radiation%20emergency
3    radiation%20emergency
4    radiation%20emergency
Name: keyword, dtype: object

In [37]:
## remove the numbers

In [38]:
train_dataset['text']=train_dataset['text'].str.replace('\d+','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\THIS PC\AppData\Local\Temp\ipykernel_14140\4125517438.py:1: SyntaxWarning: invalid escape sequence '\d'
  train_dataset['text']=train_dataset['text'].str.replace('\d+','',regex=True)


In [39]:
train_dataset['text'].head()

0    our deeds are the reason of this earthquake ma...
1                forest fire near la ronge sask canada
2    all residents asked to shelter in place are be...
3     people receive wildfires evacuation orders in...
4    just got sent this photo from ruby alaska as s...
Name: text, dtype: object

In [40]:
train_dataset['keyword']=train_dataset['keyword'].str.replace('\d+','',regex=True)


<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\THIS PC\AppData\Local\Temp\ipykernel_14140\3033268000.py:1: SyntaxWarning: invalid escape sequence '\d'
  train_dataset['keyword']=train_dataset['keyword'].str.replace('\d+','',regex=True)


In [41]:
train_dataset['keyword'].head()

0    radiation%emergency
1    radiation%emergency
2    radiation%emergency
3    radiation%emergency
4    radiation%emergency
Name: keyword, dtype: object

In [42]:
## Remove the stop words

In [43]:
import nltk

In [44]:
nltk.download('stopwords', download_dir="static/model") 


[nltk_data] Downloading package stopwords to static/model...
[nltk_data]   Package stopwords is already up-to-date!


True

In [45]:
with open('./static/model/corpora/stopwords/english', 'r') as file:
    sw =file.read().splitlines()
    

In [46]:
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [47]:
train_dataset['text']=train_dataset['text'].apply(lambda x:" ".join(x for x in x.split() if x not in sw))
train_dataset['text'].head()

0         deeds reason earthquake may allah forgive us
1                forest fire near la ronge sask canada
2    residents asked shelter place notified officer...
3    people receive wildfires evacuation orders cal...
4    got sent photo ruby alaska smoke wildfires pou...
Name: text, dtype: object

In [48]:
train_dataset['keyword']=train_dataset['keyword'].apply(lambda x:" ".join(x for x in x.split() if x not in sw))
train_dataset['keyword'].head()

0    radiation%emergency
1    radiation%emergency
2    radiation%emergency
3    radiation%emergency
4    radiation%emergency
Name: keyword, dtype: object

In [49]:
## Stemming technique

In [50]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [51]:
train_dataset['text']=train_dataset['text'].apply(lambda x:" ".join(ps.stem(x) for x in x.split()))
train_dataset['text'].head()

0            deed reason earthquak may allah forgiv us
1                 forest fire near la rong sask canada
2    resid ask shelter place notifi offic evacu she...
3          peopl receiv wildfir evacu order california
4    got sent photo rubi alaska smoke wildfir pour ...
Name: text, dtype: object

In [52]:
train_dataset['keyword']=train_dataset['keyword'].apply(lambda x:" ".join(ps.stem(x) for x in x.split()))
train_dataset['keyword'].head()

0    radiation%emerg
1    radiation%emerg
2    radiation%emerg
3    radiation%emerg
4    radiation%emerg
Name: keyword, dtype: object

In [53]:
## print the training dataset

In [54]:
train_dataset.head()

id          keyword location  \
0   1  radiation%emerg   canada   
1   4  radiation%emerg   canada   
2   5  radiation%emerg   canada   
3   6  radiation%emerg   canada   
4   7  radiation%emerg   canada   

                                                text  target  
0          deed reason earthquak may allah forgiv us       1  
1               forest fire near la rong sask canada       1  
2  resid ask shelter place notifi offic evacu she...       1  
3        peopl receiv wildfir evacu order california       1  
4  got sent photo rubi alaska smoke wildfir pour ...       1

In [55]:
## Building the vocabulary

In [56]:
from collections import Counter
vocab=Counter()

In [57]:
vocab

Counter()

In [58]:
for sentence in train_dataset['text']:
    vocab.update(sentence.split())

In [59]:
len(vocab)

14091

In [60]:
for words in train_dataset['keyword']:
    vocab.update(words.split())

In [61]:
len(vocab)

14122

In [62]:
len(vocab)

14122

In [63]:
tokens = [key for key in vocab if vocab[key]>10 and vocab[key]<75]

In [64]:
len(tokens)

1148

In [65]:
## save the vocabulary

In [66]:
def save_vocabulary(lines, file_path):
    data = '\n'.join(lines)
    file=open(file_path, 'w', encoding="utf-8")
    file.write(data)
    file.close()
save_vocabulary(tokens, "./static/model/vocabulary.txt")

In [67]:
## Divide the dataset 

In [135]:
x=train_dataset.drop('target', axis=1)

In [138]:
x=train_dataset.drop({'id','target'},axis=1)

In [139]:
x

keyword location  \
0     radiation%emerg   canada   
1     radiation%emerg   canada   
2     radiation%emerg   canada   
3     radiation%emerg   canada   
4     radiation%emerg   canada   
...               ...      ...   
7608  radiation%emerg   canada   
7609  radiation%emerg   canada   
7610  radiation%emerg   canada   
7611  radiation%emerg   canada   
7612  radiation%emerg   canada   

                                                   text  
0             deed reason earthquak may allah forgiv us  
1                  forest fire near la rong sask canada  
2     resid ask shelter place notifi offic evacu she...  
3           peopl receiv wildfir evacu order california  
4     got sent photo rubi alaska smoke wildfir pour ...  
...                                                 ...  
7608     two giant crane hold bridg collaps nearbi home  
7609  ariaahrari thetawniest control wild fire calif...  
7610                               utckm volcano hawaii  
7611  polic investig ebik collid car littl portug eb...  
7612  latest home raze northern california wildfir a...  

[7613 rows x 3 columns]

In [140]:
y=train_dataset['target']

In [141]:
y

0       1
1       1
2       1
3       1
4       1
       ..
7608    1
7609    1
7610    1
7611    1
7612    1
Name: target, Length: 7613, dtype: int64

In [161]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [143]:
x_train.shape

(6090, 3)

In [144]:
y_train.shape

(6090,)

In [145]:
x_test.shape

(1523, 3)

In [79]:
## Conver the text into  numerical values

(3, 3)

In [147]:
y_train.shape

(6090,)

In [148]:
import numpy as np

def vectorizer(ds, vocabulary):
    vectorizer_list = []
    vocab_set = set(vocabulary)  # Use a set for faster lookup
    
    for sentence in ds:
        sentence_list = np.zeros(len(vocabulary), dtype=np.float16)  # Use np.float16 to reduce memory usage
        sentence_words = set(sentence.split())  # Split and convert sentence to a set to speed up membership checking
        
        for i, word in enumerate(vocabulary):
            if word in sentence_words:  # Check if word exists in the sentence
                sentence_list[i] = 1
                
        vectorizer_list.append(sentence_list)
    
    # Convert the list to a numpy array only once
    vectorizer_list_new = np.asarray(vectorizer_list, dtype=np.float16)
    
    return vectorizer_list_new


In [172]:
import numpy as np

def vectorizer(ds, vocabulary):
    vectorizer_list = []
    vocab_set=set(vocabulary)
    for sentence in ds:
        sentence_list = np.zeros(len(vocabulary), dtype=np.float16)  # Create a zero array for each sentence
        sentence_words = set(sentence.split())  # Convert the sentence into a set of words
        
        for i, word in enumerate(vocabulary):  # Iterate over the vocabulary (list, ordered)
            if word in sentence_words:  # Check if the word exists in the sentence
                sentence_list[i] = 1  # Set the corresponding index to 1
                
        vectorizer_list.append(sentence_list)
    
    # Convert the list of arrays to a numpy array
    vectorizer_list_new = np.asarray(vectorizer_list, dtype=np.float16)
    
    return vectorizer_list_new


In [175]:
vectorizer_x_train= vectorizer(x_train['text'], tokens)
vectorizer_x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float16)

In [176]:
vectorizer_x_train=vectorizer(x_train['location'],tokens)
vectorizer_x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float16)

In [177]:
vectorizer_x_train=vectorizer(x_train['keyword'],tokens)
vectorizer_x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float16)

In [174]:
vectorizer_x_test=vectorizer(x_test['text'],tokens)
vectorizer_x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float16)

In [178]:
vectorizer_x_test=vectorizer(x_test['location'],tokens)
vectorizer_x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float16)

In [179]:
vectorizer_x_test=vectorizer(x_test['keyword'],tokens)
vectorizer_x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float16)

In [83]:
## Check the vlue of counts of y train

In [166]:
y_train.value_counts()

target
0    3468
1    2622
Name: count, dtype: int64

In [180]:
vectorizer_x_train.shape

(6090, 1148)

In [181]:
y_train.shape

(6090,)

In [182]:
vectorizer_x_test.shape

(1523, 1148)

In [183]:
vectorizer_x_train_pd = pd.DataFrame(vectorizer_x_train)
vectorizer_x_train_pd

0     1     2     3     4     5     6     7     8     9     ...  1138  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
6085   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6086   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6087   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6088   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6089   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      1139  1140  1141  1142  1143  1144  1145  1146  1147  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
6085   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6086   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6087   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6088   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6089   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[6090 rows x 1148 columns]

In [87]:
## fix the imbalance data issue

##  Model Selectiona And Model Training

In [187]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.tree import DecisionTreeClassifier
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.svm import SVC
#from sklearn.metrics import accuracy_score

In [89]:
## logistci regression model

In [189]:
#lr=LogisticRegression()
#lr.fit(vectorizer_x_train,y_train)

In [188]:
#lr_predictions = lr.predict(vectorizer_x_test)
#accuracy_score(y_test,lr_predictions)

0.6349310571240971